name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd sample-app
          npm install
      - name: Run tests
        run: |
          cd sample-app
          npm test || echo "No tests defined"
      - name: Build Docker image
        run: |
          docker build -t sample-app:latest -f docker/Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker tag sample-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest
      - name: Set ENVIRONMENT variable
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
      - name: Update Helm values file for environment
        run: |
          if [ "$ENVIRONMENT" = "prod" ]; then
            VALUES_FILE=kubernetes/helm-charts/sample-app/values-prod.yaml
          else
            VALUES_FILE=kubernetes/helm-charts/sample-app/values-dev.yaml
          fi
          sed -i "s|repository:.*|repository: ${{ secrets.DOCKERHUB_USERNAME }}/sample-app|" $VALUES_FILE
      - name: Commit and push manifest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add kubernetes/helm-charts/sample-app/values.yaml
          git commit -m "Update image repo in Helm values.yaml [skip ci]" || echo "No changes to commit"
          git push